# Generated by Django 5.2 on 2025-04-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=1)),
                ('category', models.CharField(choices=[('1', 'GENERAL'), ('2', 'OBC'), ('3', 'SC'), ('4', 'ST'), ('5', 'PWD')], default='1', max_length=1)),
                ('education', models.CharField(choices=[('1', 'High School'), ('2', 'Intermidiate'), ('3', 'UG'), ('4', 'PG'), ('5', 'PhD')], default='1', max_length=1)),
                ('courses', models.CharField(choices=[('1', 'High School'), ('2', 'Intermidiate'), ('3', 'UG'), ('4', 'PG'), ('5', 'PhD')], default='1', max_length=1)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
