# Generated by Django 5.2 on 2025-04-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_students_groups_students_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_permissions',
        ),
    ]
