# Generated by Django 5.2 on 2025-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhanaKhazana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Title of food', max_length=255)),
                ('image', models.ImageField(upload_to='pic/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('D', 'Desert'), ('S', 'Snack'), ('B', 'Beverage')], max_length=2)),
            ],
        ),
    ]
