# Generated by Django 5.2 on 2025-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khanakhazana',
            name='gender',
            field=models.CharField(choices=[('B', 'Beverage'), ('D', 'Desert'), ('S', 'Snack')], max_length=2),
        ),
    ]
