# Generated by Django 5.2 on 2025-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0003_remove_khanakhazana_gender_khanakhazana_khanaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='khanakhazana',
            name='answer',
            field=models.TextField(default='No answer provided'),
        ),
        migrations.AddField(
            model_name='khanakhazana',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='khanakhazana',
            name='description',
            field=models.TextField(default='Tell about the things', max_length=300),
        ),
        migrations.AddField(
            model_name='khanakhazana',
            name='location',
            field=models.CharField(default='Entry Gate'),
        ),
        migrations.AddField(
            model_name='khanakhazana',
            name='question',
            field=models.TextField(default='What is the color of Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='khanakhazana',
            name='khanaa',
            field=models.CharField(choices=[('S', 'Snack'), ('B', 'Beverage'), ('D', 'Dessert')], default='S', max_length=1),
        ),
    ]
