# Generated by Django 5.2 on 2025-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0004_khanakhazana_answer_khanakhazana_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khanakhazana',
            name='khanaa',
        ),
        migrations.AddField(
            model_name='khanakhazana',
            name='gate_no',
            field=models.CharField(choices=[('1', 'GATE NO-1'), ('2', 'GATE NO-2')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='khanakhazana',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='khanakhazana',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='khanakhazana',
            name='location',
            field=models.CharField(default='location'),
        ),
        migrations.AlterField(
            model_name='khanakhazana',
            name='question',
            field=models.TextField(max_length=100, null='True'),
        ),
    ]
