# Generated by Django 5.2 on 2025-04-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0005_remove_khanakhazana_khanaa_khanakhazana_gate_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Title of item', max_length=255)),
                ('image', models.ImageField(upload_to='pic/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=15, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('location', models.CharField(null=True)),
                ('question', models.TextField(max_length=100, null='True')),
                ('answer', models.TextField(default='No answer provided')),
                ('gate_no', models.CharField(choices=[('1', 'GATE NO-1'), ('2', 'GATE NO-2')], default='1', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='KhanaKhazana',
        ),
    ]
