# Generated by Django 5.2 on 2025-04-05 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0006_itemsinfo_delete_khanakhazana'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='image',
            field=models.ImageField(upload_to='lost_items/'),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='question',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
