# Generated by Django 5.2 on 2025-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0007_itemsinfo_created_at_alter_itemsinfo_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
